// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesBackendNet.Database.Data;

#nullable disable

namespace TesBackendNet.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707185037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesBackendNet.Database.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Tech Blog",
                            Url = "https://techblog.com"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Lifestyle Blog",
                            Url = "https://lifestyleblog.com"
                        });
                });

            modelBuilder.Entity("TesBackendNet.Database.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            Content = "Tutorial dasar ASP.NET Core...",
                            IsDeleted = false,
                            Title = "Belajar ASP.NET Core",
                            Views = 1500
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            Content = "Tutorial setup DbContext...",
                            IsDeleted = false,
                            Title = "Mengenal Entity Framework",
                            Views = 850
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 2,
                            Content = "Minum air putih minimal 2L...",
                            IsDeleted = false,
                            Title = "Tips Hidup Sehat",
                            Views = 340
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 2,
                            Content = "Review sepatu lari merk X...",
                            IsDeleted = false,
                            Title = "Review Sepatu Lari",
                            Views = 210
                        });
                });

            modelBuilder.Entity("TesBackendNet.Database.Models.Post", b =>
                {
                    b.HasOne("TesBackendNet.Database.Models.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("TesBackendNet.Database.Models.Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
